amzn/sketch-constructor

- models/BorderOptions/BorderOptions.js
I found a typo in the constructor of the BorderOptions model, which prevented me of creating proper BorderOptions.
> fix(borderoptions): correct typo in BorderOptions constructor

- models/Oval/Oval.js
- models/Oval/Oval.test.js
- models/Oval/index.js
- models/ShapeGroup/ShapeGroup.js
- models/index.js
I implemented the `Oval` modal in order to be able to create circles and such things. I'm curious get some feedback on it (@dbanksdesign). Especially about the curve points I wasn't sure. I'm having a hard time hard coding them, but it seems to be working fine. Do you see any problems with that?
I also added a convenience constructor just like we have it for the `Rectangular` model.
Let me know what you think 🤔
> feat(models): added Oval model and convenience constructor in ShapeGroup

- models/SharedStyle/SharedStyle.js
- models/SharedStyle/SharedStyle.test.js
*Issue #, if available:* #21
*Description of changes:* Removing duplicate instantiation of the Fill class when calling `SharedStyle.LayerStyle`
> fix(SharedStyle): fixing issue with duplicate fill instantiation

- package.json
I forgot to put index.d.ts into "files" field in package.json so type definitions will not be found.
add index.d.ts to "files" in package.json
> fix: add index.d.ts to files

- models/Text/Text.js
*Issue #25*
Attempt to prevent the generated Sketch file from crashing when using style property on a Text
> fix: wrap args.style with Style.TextStyle

- models/TextStyle/TextStyle.js
- models/TextStyle/TextStyle.test.js
- models/TextStyle/index.d.ts
Adds support for setting `lineHeight` (Line) and `kerning` (Character) to a TextStyle.
```
const textStyle = new TextStyle({
lineHeight: 38,
kerning: -1.5,
});
```
Only adds the properties to the object if the value is actually passed as an argument. By not setting this we still utilise the built in value in the font file. This is especially important for kerning since a value of `0` is **not** the same as not setting it. Setting kerning to `0` will force kerning pairs to use a fixed spacing of `0` instead of using the built in information in the font kerning pairs.
> Textstyles lineheight and kerning

- models/Bitmap/Bitmap.js
- models/Bitmap/Bitmap.test.js
- models/Bitmap/index.d.ts
- models/Bitmap/index.js
- models/Sketch/Sketch.js
- models/index.d.ts
- models/index.js
- package-lock.json
- package.json
- utils/paths.js
*Description of changes:* First draft of the image feature implementation.
@dbanksdesign you were right, the ID isn't actually an ID, its an MD5 hash of the file ;-) good catch!
Additionally I thought it would be a good idea to copy the images over to a temporary directory (`.sketch-constructor/images`) so no file changes can occur during the build process. The image files are being copied to the directory when a new bitmap object is created. The nice thing about it is, that we can then in the `build()` function also just read all files out of the directory and add them to the Sketch zip file (no need to traverse through all nodes in the JSON *wohooo* 🚀). After the build is done, I simply delete the directory to not leave behind any unused files.
Let me know what you think about the …
> feat: add bitmap model

- models/index.d.ts
AttributedString and StringAttribute are exported by js file but missed in typescript definitions
> fix: export AttributedString and StringAttribute typings

- README.md
- utils/paths.js
This option required when you manipulate with multiple Sketch files in one working dir simultaneously
> feat: added ability to change temporary directory

- models/Layer/Layer.js
- models/Layer/Layer.test.js
- models/Layer/index.d.ts
- models/SymbolMaster/SymbolMaster.js
- models/SymbolMaster/SymbolMaster.test.js
- models/SymbolMaster/index.d.ts
Issue #60 
_Description of changes:_
- updated createInstance to take in an optional list of overrides
- added updateInstance function to update overrides for existing Symbol Instances
Nested Symbol overrides are currently not supported
> feat: added support for symbol overrides

- models/SymbolMaster/SymbolMaster.js
After making shapes models immutable changeIdentifier stops to be unique. This PR returns initial behavior.
> fix: changeIdentifier is always equal to 1

- models/Artboard/index.d.ts
- models/Bitmap/index.d.ts
- models/Group/index.d.ts
- models/Layer/index.d.ts
- models/Page/index.d.ts
- models/ShapeGroup/index.d.ts
*Issue:* #70 
Refactored Bitmap type definitions to be consistent with other definitions.
> chore: refactored bitmap typings

- package-lock.json
- package.json
Upgrade docsify-cli dependency to recently released (which contains https://github.com/docsifyjs/docsify-cli/pull/65), it fixes almost all npm audit issues, to fix all issues need to wait for https://github.com/docsifyjs/docsify/pull/934 to be released
> chore: upgrade docsify-cli to v4.4.0

- models/Sketch/Sketch.js
Time to time we faced with issue when directory was removed before images were read. So I moved storage dir removing after sketch file build.
> fix: remove storage dir after Sketch was built

- package.json
Since nodejs 13.2.0 ES modules enabled by default and it would be better to exactly specify that package is written with CommonJS modules
ref: https://medium.com/@nodejs/announcing-core-node-js-support-for-ecmascript-modules-c5d6dc29b663
> chore: specify module type

- models/Artboard/Artboard.js
Artboard object needs to have `hasBackgroundColor` set to true in order to allow a background color.
> Allow to set background color

- __examples__/generating-sketch-from-style-dictionary/sketch/index.js
- models/SharedStyle/SharedStyle.js
- models/SharedStyle/SharedStyle.test.js
*Issue #84*
- Apply the same logic for `SharedStyle.TextStyle` than `SharedStyle.LayerStyle` to ensure the args delegation throw constructors.
- Added test
- Update example
> fix(SharedStyle): delegate args to Shared.TextStyle properly

- models/Sketch/Sketch.js
- models/Sketch/index.d.ts
*Issue #91*
Enable compressLevel option in the Sketch.build function to be able to compress the output file. The value is 0 by default (no compression) and it raise to 9 to highest compression (less speed).
> feat(Sketch): add compression level option to build

- models/Sketch/index.d.ts
Fix typo in the argument name for build method in the typescript definition file.
> fix(Sketch): set correct arg name in build method

- models/Page/Page.js
Page was the only class that it wasn't enable to define the object id. This PR solve this and unify the id logic in all classes
> fix(Page): enable to set id from arguments

- __tests__/utils/resizingConstraints.test.js
- models/Bitmap/Bitmap.js
- models/Layer/Layer.js
- models/Text/Text.js
- utils/maps.js
- utils/resizingConstraints.js
*Issue #97*
- Add a helper for resizingConstraint (`resizingConstraintValues` and `calculateResizingConstraintValues()`)
- Change all hard coded values to constraints
- Set `resizingConstraintValues.none` by default to all layers except text, that has `resizingConstraintValues.height`.
- Remove Bitmap model property `resizingConstraint` because extends Layers with the same value.
> feat: add resizingConstraint API

- models/Bitmap/Bitmap.js
- package-lock.json
- package.json
I found out that Sketch uses SHA1 instead of MD5 to hash filenames for images. This PR fixes that.
> fix: Use SHA1 instead of MD5 to hash image file names

- .travis.yml
- package.json
Closes #108 
This should fix failed deploy to npm
BREAKING CHANGE: support for node.js 8 is dropped
> feat: test package on node 10, 12 and 14

- __examples__/generating-sketch-from-style-dictionary/package-lock.json
- utils/maps.js
*Issue #, if available:* #112
*Description of changes:* Bottom and middle were flipped. Updated the map based on the sketch file schema: https://github.com/sketch-hq/sketch-file-format/blob/master/schema/enums/text-vertical-alignment.schema.yaml
> fix(map): fix vertical alignment map

- models/Star/Star.js
- models/Star/index.d.ts
- models/Star/index.js
- models/index.d.ts
- models/index.js
Fixes #118 
Added Star shape to models
> feat: added Star shape

- models/Blur/Blur.test.js
`Blur` didn't have the module loading line in its `index.js` so was throwing `TypeError: Blur is not a constructor` when you try to instantiate it.
e.g.:
```
const Blur = require('./models/Blur');
new Blur({});
```
would result in
```
Thrown:
TypeError: Blur is not a constructor
```
Doing similar with, for example, the `Fill` class/module would work fine though.
So this change just adds the module export to `index.js` for `Blur` and also adds a basic test to `Blur`.
> fix: add Blur module loading index, basic test

- models/Gradient/Gradient.js
*Issue #, if available:* [#162](https://github.com/amzn/sketch-constructor/issues/162)
Support using the Gradient constructor with args (`new Gradient({...})`).
(See more technical details in the attached issue.)
> Fix Gradient model constructor

- models/Meta/Meta.js
fix: Bump Sketch version to Sketch 69 which is the first version to support color variables
Issue #161 
Changes the file metadata to match that of Skech version 69, which is the earliest version of Sketch to support color variables. This is to prevent glitches with Sketch not noticing color variables exist in generated files used as libraries.
> Bump Sketch version to 69 for swatch support

- models/Meta/Meta.js
Changes the last saved data to match the current build number.
Not doing this was an oversight in #164.
I’m not aware of it causing any problems but it seems prudent to fix it anyway.
> fix(meta): Change save history to match build number

- models/InnerShadow/InnerShadow.js
- models/InnerShadow/InnerShadow.test.js
- models/InnerShadow/__InnerShadow.json
- models/InnerShadow/index.d.ts
- models/InnerShadow/index.js
- models/SharedStyle/SharedStyle.js
- models/Style/Style.js
- models/Style/index.d.ts
*Issue #, if available:* #160
*Description of changes:* Adds a new InnerShadow class and updates Style and SharedStyle to use these along side outer/regular shadows.
> Add support for inner shadows
