models/Fill/Fill.js
models/Fill/Fill.test.js
models/Rectangle/Rectangle.js
models/Style/Style.js

fix(style): fixing style bug

---

models/Artboard/Artboard.test.js
models/ExportOptions/ExportOptions.test.js
models/ExportOptions/__ExportOptions.json

test(export): adding tests for export option

---

__examples__/building-from-scratch/Swatch.js
__examples__/building-from-scratch/package.json

fix #5
*Issue #, if available:* 

docs(example): fix building-from-scratch example

---

models/index.js

In order to use Gradient, we need to export along with the other models.

feat(export format): adding Gradient model to export

---

models/index.js

Me again, found an other Model that wasn't exported. `BorderOptions`.
Cheers

Export BorderOptions

---

models/BorderOptions/BorderOptions.js

https://github.com/amzn/sketch-constructor/issues/12

fix(borderoptions): add isEnabled to args and set to true by default

---

models/Layer/Layer.js
models/Sketch/Sketch.test.js
utils/layerToClass.js

*Issue #, if available:* #18
*Description of changes:* using the proper constructor arguments to create child layers from json

fix(layer): fix layer instantiation from json

---

.travis.yml

ci(travis): getting it to deploy on master commits

---

models/index.d.ts
models/index.js

*Issue #, if available:* #28
*Description of changes:* Export SymbolInstance and SymbolMaster

fix(symbols): exporting symbol instance and master

---

__examples__/symbols/.gitignore
__examples__/symbols/index.js
__examples__/symbols/package-lock.json
__examples__/symbols/package.json
models/Layer/Layer.js
models/SymbolInstance/SymbolInstance.js
models/SymbolInstance/__SymbolInstance.json
models/SymbolMaster/SymbolMaster.js
models/SymbolMaster/SymbolMaster.test.js
models/SymbolMaster/__SymbolMaster.json
models/SymbolMaster/index.d.ts
package-lock.json

*Issue #, if available:* #30
*Description of changes:* These classes were basically empty, adding basic functionality now. Added some basic unit tests, and an example project using symbols. I need some help on the typescript definitions though because I don't know what I'm doing. 

fix(symbols): adding symbol functionality

---

models/index.js

Adds the AttributedString constructor to the main export

fix(export format): adding AttributedString and StringAttribute to export

---

models/Sketch/Sketch.js

fix: typo in Sketch model

---

models/ShapePath/ShapePath.js
models/ShapePath/index.d.ts
models/index.d.ts

feat: added typings for ShapePath

---

models/ShapeGroup/index.d.ts

fix: added missed ShapeGroup static method

---

__tests__/building.test.js
models/Artboard/Artboard.js
models/AttributedString/AttributedString.js
models/Border/Border.js
models/BorderOptions/BorderOptions.js
models/Color/Color.js
models/CurvePoint/CurvePoint.js
models/Document/Document.js
models/ExportFormat/ExportFormat.js
models/ExportOptions/ExportOptions.js
models/Fill/Fill.js
models/Gradient/Gradient.js
models/Group/Group.js
models/Layer/Layer.js
models/Meta/Meta.js
models/Oval/Oval.js
models/Page/Page.js
models/Rect/Rect.js
models/Rectangle/Rectangle.js
models/RulerData/RulerData.js
models/Shadow/Shadow.js
models/ShapeGroup/ShapeGroup.js
models/ShapePath/ShapePath.js
models/StringAttribute/StringAttribute.js
models/Style/Style.js
models/SymbolInstance/SymbolInstance.js
models/SymbolMaster/SymbolMaster.js
models/Text/Text.js
models/TextStyle/TextStyle.js
models/User/User.js

*Issue:* #44, #45 
Previous behaviour was to assign Model once per class which may produce mutations, now each class has own Model getter which returns new Object every time it called.

fix: use getters for Models

---

models/GraphicsContextSettings/GraphicsContextSettings.js
models/GraphicsContextSettings/GraphicsContextSettings.test.js
models/GraphicsContextSettings/__GraphicsContextSettings.json
models/GraphicsContextSettings/index.d.ts
models/GraphicsContextSettings/index.js
models/Shadow/index.d.ts
models/Style/Style.js
models/Style/index.d.ts
models/index.d.ts
models/index.js

*Description of changes:* Adds the GraphicsContext class.

feat: Add GraphicsContextSettings

---

models/Border/index.d.ts
models/BorderOptions/index.d.ts
models/Fill/index.d.ts
models/Gradient/index.d.ts
models/Style/Style.js
models/Style/index.d.ts

Added const enum for fill type

feat: use const enum to define relationships between getter and model

---

models/Document/Document.js

fix: Invalid Document ID assignment

---

README.md
models/Sketch/Sketch.js
models/Sketch/index.d.ts
utils/paths.js

Added static method to Sketch class to add/replace preview image

feat: added support for preview

---

models/GraphicsContextSettings/GraphicsContextSettings.js
utils/index.d.ts
utils/maps.js

feat: Support for blend mode arg in human readable format

---

models/index.d.ts

*Issue #69 *
*Description of changes:* export type of `Layer`

feat: export Layer type

---

models/Sketch/Sketch.js

Use `fs-extra` built-in methods for reading JSON

chore: use fs-extra methods to load Sketch from file

---

models/ParagraphStyle/ParagraphStyle.js
models/ParagraphStyle/index.d.ts
models/ParagraphStyle/index.js
models/StringAttribute/StringAttribute.js
models/StringAttribute/index.d.ts
models/TextStyle/TextStyle.js
models/TextStyle/index.d.ts
models/index.d.ts
models/index.js

Created `paragraphStyle` as far as it same for `StringAttribute` and `TextStyle`. Added paragraph spacing property to it.

feat: added paragraph spacing support

---

package-lock.json
package.json

In #75 I mentioned that almost all audit issues were fixed except docsify since new version were not released, this PR fixes remaining issues as far as new version of docsify was released (see https://github.com/docsifyjs/docsify/pull/934#issuecomment-566166764)

chore: fix remaining audit issues

---

__examples__/building-from-scratch/index.js
__examples__/building-from-scratch/package-lock.json
__examples__/building-from-scratch/package.json
__examples__/generating-sketch-from-style-dictionary/package-lock.json
__examples__/generating-sketch-from-style-dictionary/package.json
__examples__/generating-sketch-from-style-dictionary/sketch/ColorPage.js
__examples__/generating-sketch-from-style-dictionary/sketch/colorGroup.js
__examples__/generating-sketch-from-style-dictionary/sketch/index.js
__examples__/getting-styles-from-sketch/index.js
__examples__/getting-styles-from-sketch/package-lock.json
__examples__/getting-styles-from-sketch/package.json
__examples__/symbols/package-lock.json
__examples__/symbols/package.json

Update sketch-constructor version and sync fs-extra version in examples, fix lint

chore: update examples

---

models/Rectangle/Rectangle.js

*Issue #76 *
Enable the possibility to define the points of the rectangle or  define the cornerRadius argument. This argument could be a Number (applied to all corners) or Array[4] (applied from  topLeft to BottomRight order).

feat(Rectangle): allow to override points and set cornerRadius in points

---

utils/index.d.ts

Added typings for paths as they're exported

fix: added typings for paths

---

package-lock.json

*Description of changes:* Ran `npm audit fix`

chore(deps): fix security audit

---

models/Bitmap/Bitmap.js
models/Color/Color.js
models/Document/Document.js
models/Layer/Layer.js
models/Layer/Layer.test.js
models/Page/Page.js
models/Sketch/Sketch.js
models/Sketch/Sketch.test.js
models/Slice/Slice.js
models/Slice/index.d.ts
models/Slice/index.js
models/Style/Style.js
models/SymbolMaster/SymbolMaster.js
models/index.d.ts
models/index.js

Fixes #120 
Added Slice shape as described in commit message and run `prettier:fix` script :)

feat: added Slice shape

---

models/GraphicsContextSettings/GraphicsContextSettings.js
models/GraphicsContextSettings/GraphicsContextSettings.test.js

fix: opacity = 1 when args.opacity is zero (falsy value)

---

package-lock.json
package.json

*Description of changes:* Fixing dependabot security issue and ran `npm audit fix`

chore(deps): update dependencies for security patches

---

models/Style/Style.js

fix: remove empty textStyle object from Style

---

__tests__/building.test.js
__tests__/editing.test.js
__tests__/examples.test.js
package-lock.json
package.json

*Description of changes:* Updating Jest version to fix node-notifier security issue

chore(deps): updating jest to fix node-notifier security issue

---

docs/models.md
models/Color/Color.js
models/Color/Color.test.js
models/Color/index.d.ts
models/Document/Document.js
models/Document/index.d.ts
models/Sketch/Sketch.js
models/Sketch/index.d.ts
models/Swatch/Swatch.js
models/Swatch/Swatch.test.js
models/Swatch/index.d.ts
models/Swatch/index.js
models/index.d.ts
models/index.js

*Issue #, if available:* #141
*Description of changes:* Adds support for color variables.
Builds on work done in #142 

Support for color variables
